version: 2.1

executors:
  python-executor:
    docker:
      - image: python:3.10

jobs:
  build:
    executor: python-executor
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Build Docker image
          command: |
            docker build -t monitoring_app .

      - run:
          name: Run tests
          command: |
            docker run monitoring_app pytest tests/

      - run:
          name: Run application
          command: |
            docker run -p 5000:5000 monitoring_app

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
